#!/usr/bin/env python
#coding: utf8
def main():
 import sys
 if len(sys.argv)<5:
  print ("sql2csv: нехватает параметров\nИспользование: sql2csv ХОСТ БАЗА_ДАННЫХ ПОЛЬЗОВАТЕЛЬ ПАРОЛЬ ФАЙЛ.sql ФАЙЛ.csv\n(C) Алексей Шило,УФССП по КЧР")
  #print "./sql2csv host database user password sqlfile output.csv"
  sys.exit(2) 
 filename=sys.argv[5]  #r"./1.sql"
 f=sys.argv[6]#"/root/1.csv"
 try:
   file = open(filename,'r') #открываем файл
 except:
  print("Неудалось открыть файл скрипта:"+filename)
  sys.exit(2) 
 file2=open(f,'w')
 sql = file.readline()
 import fdb
 try:
  con = fdb.connect (host=sys.argv[1], database=sys.argv[2], user=sys.argv[3], password=sys.argv[4], charset='WIN1251')
 except  Exception, e:
  print("Ошибка при открытии базы данных:\n"+str(e))
  sys.exit(2)
 cur = con.cursor()
 try:
  cur.execute(sql.decode("UTF-8").encode('CP1251'))
 except Exception, e:
  print("Ошибка в файле скрипта:\n"+str(e))
  sys.exit(2)
 for ff in range(len(cur.description)):
  file2.write(cur.description[ff][0].decode('CP1251').encode('UTF-8')+';')
 file2.write('\n')
 result=cur.fetchall()
#rr=9
 for row in result:
  for rr in range(len(row)):
   if (str(cur.description[rr][1])[7:10]== 'str'):
    try:
     file2.write(row[rr].encode('UTF-8')+';')
    except :
     print row[rr]
   else:
    file2.write(str(row[rr])+';')
  file2.write('\n')
#file2.write('/n')

#file2.write (row[0] ,str(row[1].decode('CP1251').encode('UTF-8')) +';'+(row[2])+ ';'+str(row[3])+';'+str(row[4].decode('CP1251').e$

 file.close()
 file2.close()
 con.close()
if __name__ == "__main__":
    main()
